version: 2
jobs:
  docs-build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install OS packages
          command: |
            apt-get update
            apt-get install -y \
              texlive-base \
              texlive-latex-base \
              texlive-latex-recommended \
              texlive-fonts-recommended \
              texlive-fonts-extra \
              texlive-latex-extra \
              texlive-formats-extra \
              texlive-bibtex-extra \
              texlive-humanities \
              texlive-lang-italian \
              texinfo \
              texlive-science \
              latexmk
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Use Sphinx to make the html docs
          command: |
            pwd
            ls -l
            ./buildDocs.sh
            #touch _build/.nojekyll
      - persist_to_workspace:
          root: _build
          paths: .
          
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: _build
      - run:
          name: Disable jekyll builds
          command: touch _build/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-builds@ingv.it"
            git config user.name "CircleCI"
      - add_ssh_keys:
          fingerprints:
            - "34:2e:fa:4f:1c:09:37:11:d4:01:6a:ed:b4:fb:5c:fe"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist _build
            
workflows:
  version: 2
  build_test-docs-italia:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: main
